### ISSUE TITLE
Incorrect content-type header used during login

### ISSUE THREAD

**Issue by Petaris** [mattermost/mattermost#19211]
#### Summary
Incorrect content-type header "content-type: text/plain;charset=UTF-8" used during login ( /api/v4/users/login ) when the POST body is actually JSON.

#### Steps to reproduce
Happens every time with Mattermost 6.2.1-rc1

#### Expected behavior
Content-type header should match the body type, in this case the content-type should be "application/json".

#### Observed behavior (that appears unintentional) 
This causes issues with Web Application Firewalls, ModSecurity v3 in our case, and specifically breaks a password sanitization rule for us.  However this is likely to cause other issues as well.

#### Possible fixes
Unknown by me.

**Comment by amyblais** [comment]
@streamer45 @agnivade Would this be a bug?

**Comment by streamer45** [comment]
Hi @Petaris ,

I am not able to reproduce this. Could you give use more info on how you are building the request? Also, did you try in any other version and it worked as expected?

```
$ curl -v 'http://localhost:8065/api/v4/users/login' --data '{"login_id":"sysadmin","password":"Sys@dmin-sample1"}'
*   Trying 127.0.0.1:8065...
* Connected to localhost (127.0.0.1) port 8065 (#0)
> POST /api/v4/users/login HTTP/1.1
> Host: localhost:8065
> User-Agent: curl/7.80.0
> Accept: */*
> Content-Length: 53
> Content-Type: application/x-www-form-urlencoded
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json
< Token: feh4tmy4sj8pmgtjon5k165nxw
< Vary: Accept-Encoding
< X-Request-Id: czx1g8xkt789zcmcg1upcrkk4o
< X-Version-Id: 6.2.2.dev.31732f8ca1dc67af952780848e7a71d4.true
< Date: Mon, 20 Dec 2021 20:22:37 GMT
< Content-Length: 748
< 
{"id":"dtwejg8stfrmxydxedkp8didwa","create_at":1639061159511,"update_at":1639562123679,"delete_at":0,"username":"sysadmin","auth_data":"","auth_service":"","email":"sysadmin@sample.mattermost.com","nickname":"","first_name":"","last_name":"","position":"","roles":"system_admin system_user","allow_marketing":true,"notify_props":{"channel":"true","comments":"never","desktop":"mention","desktop_sound":"true","desktop_threads":"all","email":"true","email_threads":"all","first_name":"false","mention_keys":"","push":"mention","push_status":"away","push_threads":"all"},"last_password_update":1639061159511,"locale":"en","timezone":{"automaticTimezone":"Europe/Rome","manualTimezone":"","useAutomaticTimezone":"true"},"disable_welcome_email":false}
```

**Comment by Petaris** [comment]
Hello, I am just using the web interface that Mattermost provides, this occurs when submitting the login information.  I do have 2fa enabled though, I'm not sure if that would change the results or not.  I have not tired it in any other version.

**Comment by agnivade** [comment]
I tried with the webapp using 2fa, and I still see content-type as `application/json`. Are you sure there isn't any 3rd party middleware (like WAF) sitting between your browser and Mattermost that is not modifying the header in any way?

If there is no evidence of any external software changing the header, would you be able to open your browser network tab, and do a "copy as curl" for the login request and paste the request and the response you are seeing? Thanks.

**Comment by Petaris** [comment]
Hello,
I have confirmed that ModSecurity is not changing the content-type header and have captured the info you asked for.  Here is the curl with some parts sanitized.  The sanitized parts are in-cased with < >:

curl 'https://mattermost.<company>.com/api/v4/users/login' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0' -H 'Accept: */*' -H 'Accept-Language: en' --compressed -H 'X-Requested-With: XMLHttpRequest' -H 'Content-Type: text/plain;charset=UTF-8' -H 'Origin: https://mattermost.compsych.com' -H 'Connection: keep-alive' -H 'Cookie: rl_anonymous_id=RudderEncrypt%3AU2FsdGVkX1%2FB7Qx2zXTujlq7AGknRXaBh3KvAOx2nc%2BCh5xonAWlMvYNshb7Y4iLAYkMGOgiwIuH51g3nph%2BFA%3D%3D; rl_page_init_referrer=RudderEncrypt%3AU2FsdGVkX180YDsHplPLmL41%2BfOKVerluYRT81iJZw8%3D; rl_page_init_referring_domain=RudderEncrypt%3AU2FsdGVkX1%2BsxLMzyYU2RBEqfZhcMvhLVqmib5MA1oE%3D; rl_user_id=RudderEncrypt%3AU2FsdGVkX19n%2F%2FnCVEZhsPj0cmK8eArvHcu%2Fxn3ItOh0C9g6XGwy%2BX1kquli%2F0QQ; rl_trait=RudderEncrypt%3AU2FsdGVkX1%2FK%2FlRCvmLxv62df4UFwZ2skFouIHr7GKs%3D' --data-raw '{"device_id":"","login_id":"<MyUID>","password":"<MyPwd>","token":"<MyTkn>"}'

One thing I would like to point out, the content-type header that I refer to is for the request, not the response.  You can see here that it is using "text/plain" with a request body that is only JSON.

**Comment by streamer45** [comment]
Okay that's important cause we were looking at this from a server-side perspective. The client does indeed set `Content-Type: text/plain;charset=UTF-8`. @amyblais I think we can file a ticket for web platform maybe?

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-40751

**Comment by Petaris** [comment]
Thank you for your attention to this issue!

**Comment by Petaris** [comment]
@amyblais I noticed that the ticket has been moved back to the Server Platform and the target release has been removed.  Is there any information on when this will be looked into and fixed?

**Comment by amyblais** [comment]
The Server team will triage it and assign a dev to look at it. I'm guessing that devs didn't have a chance to take a closer look at it yet because most of our staff were off for the holidays in the past 2 weeks.

**Comment by hmhealey** [comment]
I misunderstood the issue when I moved it back to the server team. I didn't realize it was the Content-Type on the request that was set incorrectly, not the response. It looks like we actually don't set the Content-Type correctly for any POST or PUT requests, and we haven't actually done that for years at this point. We did it correctly a long time ago, but it changed at some point.

As for the target release, I can try to get something in for 6.3 for this as long as we're still in the window for that @amyblais. Fixing this seems pretty low risk since we're doing something wrong, but it's in a way that won't affect most things outside of firewalls like in this case

**Comment by amyblais** [comment]
v6.3 as a target is fine.

**Comment by hmhealey** [comment]
Alright, this fix is merged into 6.3 which'll be released in a couple weeks.

@Petaris If you'd like to double check this sooner, we could let you know when the next release candidate for 6.3 is cut

**Comment by Petaris** [comment]
@hmhealey Thanks for the work on this.  I would like to test it but I use the docker image so I'm not sure when they will release the RC for 6.3.

**Comment by Petaris** [comment]
Thanks @cpanato, I'll grab it today and give it a try!

**Comment by Petaris** [comment]
Hello, I have started an instance with 6.3.0-rc1 and I am still seeing the incorrect content-type header for the login request.

Firefox 78.15.0 ESR
Mattermost 6.3.0-rc1

This is for the login request and is a mismatch of the request header content-type specified and the actual body content type.

curl 'https://mattermost.?company?.com/api/v4/users/login' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0' -H 'Accept: */*' -H 'Accept-Language: en' --compressed -H 'X-Requested-With: XMLHttpRequest' -H 'Content-Type: text/plain;charset=UTF-8' -H 'Origin: https://mattermost.?company?.com' -H 'Connection: keep-alive' -H 'Cookie: rl_anonymous_id=RudderEncrypt%3AU2FsdGVkX1%2BiRqjikAF5wDUYmaeyeloDk0uGCZKcaDOrNKx0I7BuGVsdSkpkFRNqldLCwY0Yz7Xd8izCb3LZ6A%3D%3D; rl_page_init_referrer=RudderEncrypt%3AU2FsdGVkX180YDsHplPLmL41%2BfOKVerluYRT81iJZw8%3D; rl_page_init_referring_domain=RudderEncrypt%3AU2FsdGVkX1%2BsxLMzyYU2RBEqfZhcMvhLVqmib5MA1oE%3D; rl_user_id=RudderEncrypt%3AU2FsdGVkX1%2FNTD0jl5Z%2FNfOUS%2BFSEisgDfxX2DnVLhiqFkBzda3PNziGrqFwOrvm; rl_trait=RudderEncrypt%3AU2FsdGVkX18sHNXBzz145kjktY6l5FUqCzvFsXOoRkk%3D' --data-raw '{"device_id":"","login_id":"?MyUID?","password":"?MyPwd?","token":"?MyToken?"}'


Am I missing something?

Thank you,

Justin

**Comment by amyblais** [comment]
@Petaris My apologies, this is included in RC-2.

**Comment by Petaris** [comment]
@amyblais Ok, no problem.

@cpanato is 6.3.0-rc2 available for MM Team Edition Docker image?

Thanks!

**Comment by cpanato** [comment]
it is 
```
$ crane digest mattermost/mattermost-team-edition:6.3.0-rc2
sha256:764c9ef3b0104d7ec39dc5f919d870b0c12dbd28c12fd4ba629b067b0bacdebe
```

**Comment by Petaris** [comment]
@cpanato Thanks!  I'll grab that and test.

**Comment by Petaris** [comment]
@amyblais, @hmhealey, and @cpanato  I can happily say  that the issue is fixed based on my testing!  :D

Thank you!
