### ISSUE TITLE
Saved messages display limit

### ISSUE THREAD

**Issue by olodar** [mattermost/mattermost#21905]
Hi there,
We have noticed some of older saved messages... disappeared. But those messages isn't really disappeared, of course, they just simply not displaying more than **_60_**, in "Saved posts" menu, and these "lost" messages can be found manually.
Previously I already wrote about search limits here - https://forum.mattermost.com/t/how-to-extend-search-limit/11680 and I didn't get any solution. However, this problem can be solved by enabling bleve search, which now working perfectly:
<img width="300" alt="Capture" src="https://user-images.githubusercontent.com/32993068/208315829-a019bea3-e70f-4155-b5cd-8fefa60a09e1.PNG">.
So, my question: is there any way to extend or disable this limit?
Also, I suggest to use bleve search also for saved posts, to prevent those unnecessary limits.

Thank you!

**Comment by amyblais** [comment]
I was able to reproduce it, opened https://mattermost.atlassian.net/browse/MM-49216.

**Comment by olodar** [comment]
> @olodar What Mattermost server version are you on?

7.5.1

You can try it by yourself - save around 70 posts and you'll see that only 60 (or 61?) posts can be displayed.
BTW, I mean bleve solves search limit for messages/files (without bleve, limit is 100 messages/files), but it is not working for saved posts.

**Comment by olodar** [comment]
Is there any movements? Already out 8 version, but still no any fixes of this stupid bug.

**Comment by olodar** [comment]
Finally fixed in 9.3. But only on desktop (web) client, mobile (Android) client still has the same bug.

**Comment by Tragen** [comment]
For me it's not fixed. I still have the same problem.

**Comment by olodar** [comment]
> For me it's not fixed. I still have the same problem.

How much saved messages you can see?

**Comment by M-ZubairAhmed** [comment]
Reopened as Help Wanted Ticket https://github.com/mattermost/mattermost/issues/26192

**Comment by Tragen** [comment]
I've installed 10.2.0 and this bug is still not fixed. Why was it completed? Do I need to change some settings?

**Comment by M-ZubairAhmed** [comment]
Hi @Tragen this bug is opened as H/W ticket see the above comment. You are welcome to submit a fix for it

**Comment by olodar** [comment]
> I've installed 10.2.0 and this bug is still not fixed. Why was it completed? Do I need to change some settings?

I can't believe they don't care about such a little, but highly annoying bug.
