### ISSUE TITLE
Upgrading from 9.0.0 to 9.2.3 - Error: unable to load Mattermost translation files (Self-Host)

### ISSUE THREAD

**Issue by Shimrockx** [mattermost/mattermost#25584]
#### Summary
While upgrading from 9.0.0 to 9.2.3 an error happened when starting the mattermost server 
"Error: unable to load Mattermost translation files"

#### Steps to reproduce
Install the 9.0.0 mattermost version entreprise edition on a bare metal server, and reproduce the upgrading steps from the documentation to upgrade to 9.2.3. [Upgrade Mattermost Server documentation](https://docs.mattermost.com/upgrade/upgrading-mattermost-server.html)

#### Expected behavior
Translation templates have errors when starting the server
Here are the error logs I noticed on the following languages: 
Error: unable to load Mattermost translation files: unable to parse translation #157 because template: Няправільны параметр {{. Імя}}.:1: function "Імя" not defined

Error: unable to load Mattermost translation files: unable to parse translation #180 because template: Ο χρήστης {{.User}} προστέθηκε στο κανάλι {{.Το Channel}}.:1: function "Channel" not defined

Error: unable to load Mattermost translation files: unable to parse translation #1124 because template: पासवर्ड के साथ बाहरी मैटरमोस्ट सिस्टम एडमिन को निम्नलिखित एईएस 256-बिट एन्क्रिप्टेड आमंत्रण भेजें। वे आमंत्रण स्वीकार करने लिए `{. Command}}` स्लैश कमांड का उपयोग करेंगे।

There are certainly many other languages involved, but I haven't tested them all.

#### Observed behavior (that appears unintentional) 
Full error logs :

```console
Nov 30 08:45:28 mattermost mattermost[177675]: Error: unable to load Mattermost translation files: unable to parse translation #157 because template: Няправільны параметр {{. Імя}}.:1: function "Імя" not defined
Nov 30 08:45:28 mattermost mattermost[177675]: map[id:api.context.invalid_param.app_error translation:Няправільны параметр {{. Імя}}.]
Nov 30 08:45:28 mattermost mattermost[177675]: Usage:
Nov 30 08:45:28 mattermost mattermost[177675]:   mattermost [flags]
Nov 30 08:45:28 mattermost mattermost[177675]:   mattermost [command]
Nov 30 08:45:28 mattermost mattermost[177675]: Available Commands:
Nov 30 08:45:28 mattermost mattermost[177675]:   completion  Generate the autocompletion script for the specified shell
Nov 30 08:45:28 mattermost mattermost[177675]:   db          Commands related to the database
Nov 30 08:45:28 mattermost mattermost[177675]:   export      Export data from Mattermost
Nov 30 08:45:28 mattermost mattermost[177675]:   help        Help about any command
Nov 30 08:45:28 mattermost mattermost[177675]:   import      Import data.
Nov 30 08:45:28 mattermost mattermost[177675]:   jobserver   Start the Mattermost job server
Nov 30 08:45:28 mattermost mattermost[177675]:   server      Run the Mattermost server
Nov 30 08:45:28 mattermost mattermost[177675]:   version     Display version information
Nov 30 08:45:28 mattermost mattermost[177675]: Flags:
Nov 30 08:45:28 mattermost mattermost[177675]:   -c, --config string   Configuration file to use.
Nov 30 08:45:28 mattermost mattermost[177675]:   -h, --help            help for mattermost
Nov 30 08:45:28 mattermost mattermost[177675]: Use "mattermost [command] --help" for more information about a command.
Nov 30 08:45:28 mattermost systemd[1]: mattermost.service: Main process exited, code=exited, status=1/FAILURE
Nov 30 08:45:28 mattermost systemd[1]: mattermost.service: Failed with result 'exit-code'.
Nov 30 08:45:29 mattermost systemd[1]: Stopped Mattermost.
```

#### Possible fixes
The files concerned are in the i18n folder at the root of the mattermost installation.
You can solve the problems by renaming the language files concerned if you don't need them
example:
```shell
sudo mv i18n/be.json i18n/be.json.back
```
You can also correct the template yourself if you know the language, in order to contribute to the mattermost translation.

For my part, I made a copy elsewhere of the language files for my team and deleted all the other languages so as not to encounter this problem again.
```shell
cd {install-path}
sudo cp i18n/en.json ~/en.json
sudo rm i18n/*.json
sudo mv ~/en.json i18n/en.json
```

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-55995.

**Comment by agnivade** [comment]
Indeed, I can confirm that those translation files are incorrect. 

@lieut-data @cwarnermm - we'll need to fix the affected files from Weblate. Perhaps also add a unit test to verify any non-en files as well.

**Comment by lieut-data** [comment]
@agnivade, the server is supposed to ignore all but the whitelisted (and supported) translation files. I wonder if we can find out what's unique to these installations, since it's not a widespread issue?

**Comment by agnivade** [comment]
That's strange, I am not able to reproduce the issue locally. Looking at the code, we have a hardcoded set of supported locales and `be.json`, `hi.json` aren't included in that. So I am failing to see how can this happen, but clearly it's happening nonetheless.

@saturninoabril - Wondering if we can get some help from QA in trying to repro this? Basically 9.2 is throwing an error trying to load translation files which it shouldn't even be doing.

**Comment by saturninoabril** [comment]
I tried to repro and can't reproduce either. Not sure how those unsupported locales get loaded but I can see invalid translation entries such as those within the double curly brackets (`{{...}}`) in which either it gets translated or has space after the period.

Ex.
```diff
- Няправільны параметр {{. Імя}}.
+ Няправільны параметр {{.Name}}.
```

```diff
- Ο χρήστης {{.User}} προστέθηκε στο κανάλι {{.Το Channel}}.
+ Ο χρήστης {{.User}} προστέθηκε στο κανάλι {{.ΤοChannel}}.
```

Introduced by https://github.com/mattermost/mattermost/pull/24683 and was first observed by @enahum (https://github.com/mattermost/mattermost/pull/24683#issuecomment-1749963810)

**Comment by agnivade** [comment]
Going to close this as cannot reproduce. Happy to reopen If someone can post valid repro steps. And looks like anyways the problem is easily fixed by just removing the unnecessary files.

**Comment by grosjo** [comment]
Same issue on upgrading to mattermost 11

**Comment by lieut-data** [comment]
@grosjo, can you share the error logs you're seeing?

**Comment by Shimrockx** [comment]
I am almost certain that your current problem with Mattermost 11 is due to the fact that you forgot to delete all files, except for the data and custom directories, from the current Mattermost directory.
As @beastofbobmin suggest to do : 
```shell
sudo find mattermost/ mattermost/client/ -mindepth 1 -maxdepth 1 \! \( -type d \( -path mattermost/client -o -path mattermost/client/plugins -o -path mattermost/config -o -path mattermost/logs -o -path mattermost/plugins -o -path mattermost/data \) -prune \) | sort | sudo xargs rm -r
```

See point 7 of [upgrading mattermost server](https://docs.mattermost.com/administration-guide/upgrade/upgrading-mattermost-server.html) for more information.
