### ISSUE TITLE
Having a notification in draft section

### ISSUE THREAD

**Issue by syedaliObjects** [mattermost/mattermost#30140]
I have a issue with mattermost that need to be fixed.

![Image](https://github.com/user-attachments/assets/d039f196-16a7-446f-95f0-906a86f44fbc)

having notifications on draft when go there 

1. Send a message to someone
2. delete the message by clicking on delete button
3. now you have a notification ( message has been deleted )
4. click on that notification and wright something in the reply box now you have a notification in your draft section.
5. now click on the cross icon to remove the notification ( message has been deleted ).
6. This is the way you can replicate the issue

**Comment by amyblais** [comment]
Hi @syedaliObjects, I wasn't able to reproduce it just now.

1. What Mattermost server version are you on?
2. What OS and version are you on?
3. Are you able to reproduce this issue on our community server here https://community.mattermost.com/?

**Comment by syedaliObjects** [comment]
Hi,
I am unable to replicate the issue on https://community.mattermost.com/.

is there any command or any thing that can clean all notification in draft section.

**Comment by syedaliObjects** [comment]
Hi @amyblais ,
Today I have received the update in mattermost desktop application now I am getting this screen.

![Image](https://github.com/user-attachments/assets/d084618f-f5d0-4fe5-9c90-8748fe16387e)

**Comment by syedaliObjects** [comment]
hi @amyblais,
any update?

**Comment by amyblais** [comment]
Hi @syedaliObjects!

**Issue 1: Having a notification in draft section**

Since your server version is quite old, would you be open to upgrading to a more recent version? We currently support v9.11.0 and newer versions.

**Issue 2: Blank screen in desktop app**
This issue was fixed in desktop app v5.11.2. Would you be open to updating to the latest desktop app version?

**Comment by syedaliObjects** [comment]
Hi @amyblais 
I have updated mattermost server now I am using **v9.11.16**
My draft notification issue still here

Please help me to fix this problem.

**Comment by amyblais** [comment]
Feel free to post about this issue on our troubleshooting forums either at https://forum.mattermost.com/ or at https://community.mattermost.com/core/channels/peer-to-peer-help.

**Comment by syedaliObjects** [comment]
The issue has been resolved successfully.
Thanks for your support
